name: Sync Upstream
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write # <--- Add this line
    steps:
      - name: Sync with upstream
        uses: tgymnich/fork-sync@v2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: danny-avila
          base: main
          head: main
